name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  plugin-ci:
    uses: eefsowa-source/eon-ci/.github/workflows/reusable-ci.yml@0e381ce34845c49c59b581e015bfa709ebd5549b
    with:
      product_name: "EON-Vari mu DSP"
      plugin_target: eonchild
      au_type: aufx
      au_subtype: Eonc
      au_manufacturer: Eonn
